# Generated by Django 5.2 on 2025-05-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('Id_Bot', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Token', models.CharField(max_length=250)),
                ('Numero', models.CharField(max_length=50, null=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Bots',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('Id_Carrera', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Facultad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('Id_FAQ', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=500)),
                ('Respuesta', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'FAQS',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('Id_Materia', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Chat', models.BigIntegerField()),
                ('Usuario', models.CharField(max_length=150)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('Id_Anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=250)),
                ('Contenido', models.TextField()),
                ('Fecha', models.DateField()),
                ('Activo', models.BooleanField(default=True)),
                ('Id_Bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bot')),
            ],
            options={
                'db_table': 'Anuncios',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Id_Docente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.carrera')),
            ],
            options={
                'db_table': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Id_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Semestre', models.IntegerField()),
                ('Telefono', models.CharField(max_length=50)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.carrera')),
                ('Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.usuario')),
            ],
            options={
                'db_table': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Materia_Ofertada',
            fields=[
                ('Id_Materia_Ofertada', models.AutoField(primary_key=True, serialize=False)),
                ('Semestre', models.IntegerField()),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Final', models.DateField()),
                ('Modulo', models.CharField(max_length=50)),
                ('Año', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('Id_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.docente')),
                ('Id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.materia')),
            ],
            options={
                'db_table': 'Materia_Ofertadas',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('Id_Inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.estudiante')),
                ('Id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.materia_ofertada')),
            ],
            options={
                'db_table': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Bot',
            fields=[
                ('Id_Solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('Consulta', models.TextField()),
                ('Respuesta', models.TextField()),
                ('Id_Bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bot')),
                ('Id_FAQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.faq')),
                ('Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.usuario')),
            ],
            options={
                'db_table': 'Solicitudes_Bot',
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('Id_Accion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Plataforma', models.CharField(max_length=100)),
                ('Accion', models.CharField(max_length=250)),
                ('Id_Solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.solicitud_bot')),
            ],
            options={
                'db_table': 'Acciones',
            },
        ),
    ]
