# Generated by Django 5.2.1 on 2025-05-12 22:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_accion_created_at_accion_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('Id_Recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('Recomendacion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Id_Bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bot')),
            ],
        ),
    ]
